// Tests for the hyperdimensional layer — the Node port of
// tests/test_gudda_ingestion.py.
//
// Three kinds of test here, and the distinction matters:
//
//  1. PARITY. Fixtures in gudda-parity.json were generated by running the
//     original Python (gudda_bridge.py / sentinel_bridge.py, preserved on the
//     `Gudda-Ingestion-original` branch) and captured verbatim. These assert
//     the port produces the same bits, not merely something plausible. If you
//     change an encoder and these fail, you have changed behaviour.
//  2. PROPERTIES. The VSA algebra the design relies on — binding is
//     invertible, bundling stays near its inputs, unrelated keys are
//     quasi-orthogonal.
//  3. CALIBRATION. Two tests pin behaviour that is currently *wrong*: the
//     untrained signal prototypes and the sentinel's false-positive rate.
//     They exist so that fixing either one fails loudly here rather than
//     silently changing what the bot does in production. Read them before
//     turning on `hd_gate_enabled` or `sentinel_quarantine`.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  BinaryHDVector, HDVector, bundleAll, encodeText, encodeTurn,
  cosineSimilarity, xnorPopcountSimilarity,
  sdmSnrThreshold, sdmMemRadius, sdmCentroidRadius,
  packBits, unpackBits, nativeAvailable,
  DiscordSentinel, DiscordEventEncoder, EVENT_FIELDS,
  HDMemoryStore,
} from '../src/gudda/index.js';
import { MT19937, stableHash } from '../src/gudda/rng.js';
import { hdPreclassify, hdAnySignal, HD_SIM_THRESHOLD } from '../src/proactive.js';
import * as db from '../src/db.js';

const PARITY = JSON.parse(
  readFileSync(new URL('./gudda-parity.json', import.meta.url), 'utf8'),
);
const D = PARITY.dim;

const bits = (v) => Array.from(v.toBits()).join('');
const mapOf = (v) => Array.from(v.data);

function withDb(fn) {
  return async () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'nodebot-gudda-test-'));
    db.initDb(path.join(dir, 'test.db'));
    try {
      await fn();
    } finally {
      db.closeDb();
      rmSync(dir, { recursive: true, force: true });
    }
  };
}

// ============================================================================
// 1. Parity with the Python original
// ============================================================================

test('stableHash matches the Python 64-bit rotate/multiply hash', () => {
  // Pinned from CPython: _stable_hash("speaker") on the original.
  assert.equal(typeof stableHash('speaker'), 'bigint');
  assert.equal(stableHash(''), 0x3141592653589793n);
  // Distinct inputs, distinct hashes — including past the BMP.
  const seen = new Set(['a', 'b', 'speaker', '🎧', 'hey max'].map((k) => stableHash(k)));
  assert.equal(seen.size, 5);
});

test('MT19937 reproduces CPython random.Random draw-for-draw', () => {
  // Captured from CPython: random.Random(0).getrandbits(32) x4 …
  const g = new MT19937(0);
  assert.deepEqual([g.next(), g.next(), g.next(), g.next()],
    [3626764237, 1654615998, 3255389356, 3823568514]);
  // … and random.Random(0).random() x2, which is genrand_res53 over the
  // same stream, so it pins the float path too.
  const f = new MT19937(0);
  assert.equal(f.random(), 0.8444218515250481);
  assert.equal(f.random(), 0.7579544029403025);
});

test('nextBit agrees with random() < 0.5 over a long run', () => {
  const a = new MT19937(12345);
  const b = new MT19937(12345);
  for (let i = 0; i < 500; i += 1) {
    assert.equal(a.nextBit(), b.random() < 0.5 ? 1 : 0, `draw ${i}`);
  }
});

test('BinaryHDVector.fromKey is bit-exact with Python', () => {
  for (const [key, want] of Object.entries(PARITY.fromKey)) {
    assert.equal(bits(BinaryHDVector.fromKey(key, D)), want, `key ${JSON.stringify(key)}`);
  }
});

test('HDVector.fromKey is bit-exact with Python', () => {
  for (const [key, want] of Object.entries(PARITY.mapFromKey)) {
    assert.deepEqual(mapOf(HDVector.fromKey(key, D)), want, `key ${key}`);
  }
});

test('bind and bundle are bit-exact with Python', () => {
  const a = BinaryHDVector.fromKey('a', D);
  const b = BinaryHDVector.fromKey('b', D);
  assert.equal(bits(a.bind(b)), PARITY.bind);
  assert.equal(bits(a.bundle(b)), PARITY.bundle2);
});

test('permute is bit-exact with Python at every word boundary', () => {
  const v = BinaryHDVector.fromKey('perm', D);
  for (const [shift, want] of Object.entries(PARITY.permute)) {
    assert.equal(bits(v.permute(Number(shift))), want, `shift ${shift}`);
  }
});

test('bundleAll is bit-exact with Python for odd and even counts', () => {
  const odd = Array.from({ length: 5 }, (_, i) => BinaryHDVector.fromKey(`v${i}`, D));
  assert.equal(bits(bundleAll(odd, D)), PARITY.bundleAll);
  const even = Array.from({ length: 4 }, (_, i) => BinaryHDVector.fromKey(`w${i}`, D));
  assert.equal(bits(bundleAll(even, D)), PARITY.bundleAllEven);
});

test('encodeText is bit-exact with Python, including surrogate pairs', () => {
  for (const [text, want] of Object.entries(PARITY.encodeText)) {
    assert.equal(bits(encodeText(text, D)), want, `text ${JSON.stringify(text.slice(0, 30))}`);
  }
});

test('encodeTurn is bit-exact with Python', () => {
  assert.equal(bits(encodeTurn('jordan', 'deploy is failing', 1.0, 'text', D)),
    PARITY.encodeTurn.int_ts);
  assert.equal(bits(encodeTurn('priya', 'voice line', 1234.5, 'voice', D)),
    PARITY.encodeTurn.float_ts);
  assert.equal(bits(encodeTurn('max', '', 2.0, 'text', D)),
    PARITY.encodeTurn.empty_text);
});

test('MAP operations are bit-exact with Python', () => {
  const m1 = HDVector.fromKey('m1', D);
  const m2 = HDVector.fromKey('m2', D);
  assert.deepEqual(mapOf(m1.bind(m2)), PARITY.mapOps.bind);
  assert.deepEqual(mapOf(m1.bundle(m2)), PARITY.mapOps.bundle);
  assert.deepEqual(mapOf(m1.permute(3)), PARITY.mapOps.permute3);
  assert.equal(bits(m1.toBinary()), PARITY.mapOps.toBinary);
});

test('SDM radii match Python at both dimensions', () => {
  for (const [dim, want] of Object.entries(PARITY.sdm)) {
    const d = Number(dim);
    assert.deepEqual([sdmSnrThreshold(d), sdmMemRadius(d), sdmCentroidRadius(d)], want);
  }
});

test('sentinel encoding and a full observe sequence match Python', () => {
  const enc = new DiscordEventEncoder(D);
  const { conj, disj, bound } = enc.encode('MESSAGE_BURST',
    { channel_id: '123', rate: '0.80', window_seconds: '10' });
  assert.deepEqual(mapOf(conj), PARITY.sentinelEncode.conj);
  assert.deepEqual(mapOf(disj), PARITY.sentinelEncode.disj);
  assert.deepEqual([...bound.keys()].sort(), PARITY.sentinelEncode.boundKeys);

  const s = new DiscordSentinel({ dim: D });
  const events = [
    ['MESSAGE_BURST', { channel_id: '1', rate: '0.5', window_seconds: '10' }],
    ['MESSAGE_BURST', { channel_id: '1', rate: '0.5', window_seconds: '10' }],
    ['MESSAGE_BURST', { channel_id: '1', rate: '0.6', window_seconds: '10' }],
    ['MENTION_STORM', { target_user_id: '9', mention_count: '40', source_count: '12' }],
    ['MEMBER_JOIN', { user_id: '7', role_count: '1' }],
  ];
  events.forEach(([type, fields], i) => {
    const r = s.observe(type, fields);
    const want = PARITY.sentinelSequence[i];
    assert.equal(r.verdict, want.verdict, `event ${i} verdict`);
    assert.ok(Math.abs(r.similarity - want.similarity) < 1e-12, `event ${i} similarity`);
    assert.ok(Math.abs(r.anomalyScore - want.anomalyScore) < 1e-12, `event ${i} score`);
  });
  mapOf(s.baseline).slice(0, 8).forEach((x, i) => {
    assert.ok(Math.abs(x - PARITY.sentinelBaselineHead[i]) < 1e-12, `baseline[${i}]`);
  });
});

// ============================================================================
// 2. VSA properties
// ============================================================================

test('the native PyO3 path is absent — this is the pure implementation', () => {
  assert.equal(nativeAvailable(), false);
});

test('fromKey is deterministic and distinct keys are quasi-orthogonal', () => {
  assert.equal(bits(BinaryHDVector.fromKey('same', D)), bits(BinaryHDVector.fromKey('same', D)));
  const a = BinaryHDVector.fromKey('alpha', D);
  const b = BinaryHDVector.fromKey('beta', D);
  assert.equal(a.xnorPopcountSimilarity(a), 1.0);
  // Two unrelated vectors agree on ~half their bits.
  assert.ok(Math.abs(a.xnorPopcountSimilarity(b) - 0.5) < 0.15);
});

test('XOR binding is invertible', () => {
  const a = BinaryHDVector.fromKey('a', D);
  const b = BinaryHDVector.fromKey('b', D);
  const bound = a.bind(b);
  assert.equal(bound.bind(b).xnorPopcountSimilarity(a), 1.0);
  // And the bound pair is unlike either input.
  assert.ok(bound.xnorPopcountSimilarity(a) < 0.7);
});

test('bundleAll stays close to each of its inputs', () => {
  const vecs = ['p', 'q', 'r'].map((k) => BinaryHDVector.fromKey(k, D));
  const bundled = bundleAll(vecs, D);
  for (const v of vecs) {
    assert.ok(bundled.xnorPopcountSimilarity(v) > 0.6, 'bundle should resemble its members');
  }
});

test('bundleAll breaks an even split to zero', () => {
  const a = BinaryHDVector.fromBits([1, 1, 0, 0], 4);
  const b = BinaryHDVector.fromBits([1, 0, 1, 0], 4);
  // counts = [2,1,1,0], threshold = 1, so only a strict majority survives.
  assert.deepEqual(Array.from(bundleAll([a, b], 4).toBits()), [1, 0, 0, 0]);
});

test('encodeText is deterministic, order-sensitive, and empty-safe', () => {
  assert.equal(bits(encodeText('hello world', D)), bits(encodeText('hello world', D)));
  assert.notEqual(bits(encodeText('hello world', D)), bits(encodeText('world hello', D)));
  assert.deepEqual(Array.from(encodeText('', D).toBits()), new Array(D).fill(0));
});

test('encodeTurn separates turns that differ in any single role', () => {
  const base = encodeTurn('jordan', 'the build broke', 100, 'text', D);
  const others = [
    encodeTurn('priya', 'the build broke', 100, 'text', D),
    encodeTurn('jordan', 'the build is fine', 100, 'text', D),
    encodeTurn('jordan', 'the build broke', 101, 'text', D),
    encodeTurn('jordan', 'the build broke', 100, 'voice', D),
  ];
  for (const other of others) {
    assert.ok(base.xnorPopcountSimilarity(other) < 1.0);
  }
  assert.equal(base.xnorPopcountSimilarity(encodeTurn('jordan', 'the build broke', 100, 'text', D)), 1.0);
});

test('MAP cosine similarity is clamped and signed', () => {
  const v = HDVector.fromKey('cos', D);
  assert.equal(v.cosineSimilarity(v), 1.0);
  const neg = new HDVector(D, Float64Array.from(v.data, (x) => -x));
  assert.equal(v.cosineSimilarity(neg), -1.0);
  assert.equal(HDVector.zeros(D).cosineSimilarity(v), 0);
});

test('standalone similarity helpers agree with the vector methods', () => {
  assert.equal(cosineSimilarity([1, -1, 1], [1, -1, 1]), 1);
  assert.equal(xnorPopcountSimilarity([1, 0, 1, 0], [1, 0, 1, 0]), 1);
  assert.equal(xnorPopcountSimilarity([1, 0, 1, 0], [0, 1, 0, 1]), 0);
  assert.throws(() => cosineSimilarity([1], [1, 2]), /length mismatch/);
});

test('dimension mismatches are rejected rather than silently truncated', () => {
  const a = BinaryHDVector.fromKey('a', 64);
  const b = BinaryHDVector.fromKey('b', 128);
  assert.throws(() => a.bind(b), /dim mismatch/);
  assert.throws(() => a.xnorPopcountSimilarity(b), /dim mismatch/);
});

test('bit packing round-trips, including a non-byte-aligned dimension', () => {
  for (const dim of [1, 7, 8, 63, 64, 256, 10000]) {
    const v = BinaryHDVector.fromKey(`pack${dim}`, dim);
    const original = v.toBits();
    assert.deepEqual(Array.from(unpackBits(packBits(original), dim)), Array.from(original), `dim ${dim}`);
  }
});

test('similarity ignores padding bits past the declared dimension', () => {
  // dim 100 leaves 28 unused bits in the last 32-bit word; a shift pushes
  // real bits into them, and they must not count toward the score.
  const v = BinaryHDVector.fromKey('pad', 100);
  assert.equal(v.permute(50).xnorPopcountSimilarity(v.permute(50)), 1.0);
});

// ============================================================================
// 3. Sentinel behaviour
// ============================================================================

test('sentinel starts empty and seeds its baseline on the first event', () => {
  const s = new DiscordSentinel({ dim: D });
  assert.equal(s.initialized, false);
  assert.equal(s.baseline, null);
  const r = s.observe('MEMBER_JOIN', { user_id: '1', role_count: '0' });
  assert.equal(r.verdict, 'INIT');
  assert.equal(r.anomalyScore, 0);
  assert.equal(s.initialized, true);
  assert.equal(s.eventCount, 1);
});

test('sentinel allows a repeat of the event it was seeded with', () => {
  const s = new DiscordSentinel({ dim: D });
  const fields = { user_id: '1', role_count: '0' };
  s.observe('MEMBER_JOIN', fields);
  const r = s.observe('MEMBER_JOIN', fields);
  assert.equal(r.verdict, 'ALLOW');
  assert.ok(r.anomalyScore < 0.15);
});

test('sentinel reset clears everything', () => {
  const s = new DiscordSentinel({ dim: D });
  s.observe('MEMBER_JOIN', { user_id: '1', role_count: '0' });
  s.reset();
  assert.equal(s.initialized, false);
  assert.equal(s.baseline, null);
  assert.equal(s.eventCount, 0);
});

test('sentinel verdict thresholds are ordered and configurable', () => {
  const s = new DiscordSentinel({ dim: D, warnThreshold: 0.1, quarantineThreshold: 0.2 });
  assert.ok(s.warnThreshold < s.quarantineThreshold);
  assert.equal(s.alpha, 0.98);
});

test('every declared event type encodes without error', () => {
  const enc = new DiscordEventEncoder(D);
  for (const [type, fields] of Object.entries(EVENT_FIELDS)) {
    const values = Object.fromEntries(fields.map((f) => [f, 'x']));
    const { conj } = enc.encode(type, values);
    assert.equal(conj.dim, D);
  }
});

test('unknown event fields are ignored, not encoded', () => {
  const enc = new DiscordEventEncoder(D);
  const withJunk = enc.encode('MEMBER_JOIN', { user_id: '1', role_count: '0', nonsense: 'zzz' });
  const without = enc.encode('MEMBER_JOIN', { user_id: '1', role_count: '0' });
  assert.deepEqual(mapOf(withJunk.conj), mapOf(without.conj));
});

// ============================================================================
// 4. HD memory store
// ============================================================================

test('store accumulates turns and converges on repeated content', () => {
  const store = new HDMemoryStore('1', D);
  assert.equal(store.getConjunctive(), null);

  const vec = encodeTurn('jordan', 'always the same thing', 1, 'text', D);
  for (let i = 0; i < 10; i += 1) store.ingestTurn(vec);
  assert.equal(store.turnCount, 10);
  // Ingesting one vector repeatedly makes the accumulator that vector.
  assert.equal(store.getConjunctive().xnorPopcountSimilarity(vec), 1.0);
});

test('store drifts toward newer content without saturating', () => {
  const store = new HDMemoryStore('1', D);
  const early = encodeTurn('a', 'the original topic entirely', 1, 'text', D);
  for (let i = 0; i < 5; i += 1) store.ingestTurn(early);
  const before = store.getConjunctive().xnorPopcountSimilarity(early);

  const late = encodeTurn('b', 'a completely different subject now', 2, 'text', D);
  for (let i = 0; i < 40; i += 1) store.ingestTurn(late);
  const after = store.getConjunctive().xnorPopcountSimilarity(early);

  assert.ok(after < before, 'sustained new content should pull the accumulator away');
  assert.ok(store.getConjunctive().xnorPopcountSimilarity(late) > 0.9);
});

test('the disjunctive accumulator samples sparsely', () => {
  const store = new HDMemoryStore('1', D);
  const vec = encodeTurn('a', 'x', 1, 'text', D);
  store.ingestTurn(vec);
  assert.notEqual(store.getDisjunctive(), null, 'first turn seeds it');
  for (let i = 0; i < 3; i += 1) store.ingestTurn(vec);
  // Turns 2-4 are skipped; only every 5th (turnCount % 5 === 1) is folded in.
  assert.equal(store.turnCount, 4);
});

test('profile vectors superpose card fields and clear when the card empties', () => {
  const store = new HDMemoryStore('1', D);
  store.setProfileVector('42', { goals: 'ship the bot', constraints: 'mobile only' });
  const v = store.getProfileVector('42');
  assert.ok(v);
  assert.ok(v.xnorPopcountSimilarity(BinaryHDVector.fromKey('goals:ship the bot', D)) > 0.6);

  store.setProfileVector('42', {});
  assert.equal(store.getProfileVector('42'), null);
});

test('distinct members get distinguishable profile vectors', () => {
  const store = new HDMemoryStore('1', D);
  store.setProfileVector('1', { goals: 'write a novel' });
  store.setProfileVector('2', { goals: 'run a marathon' });
  const sim = store.getProfileVector('1').xnorPopcountSimilarity(store.getProfileVector('2'));
  assert.ok(sim < 0.7, `expected distinguishable profiles, got ${sim}`);
});

test('store round-trips through SQLite', withDb(() => {
  const store = new HDMemoryStore('77', D);
  for (let i = 0; i < 6; i += 1) {
    store.ingestTurn(encodeTurn('jordan', `turn number ${i}`, i, 'text', D));
  }
  store.setProfileVector('42', { goals: 'ship it' });
  const conj = bits(store.getConjunctive());
  const disj = bits(store.getDisjunctive());
  const prof = bits(store.getProfileVector('42'));
  store.save(db);

  const restored = new HDMemoryStore('77', D);
  restored.load(db);
  assert.equal(bits(restored.getConjunctive()), conj);
  assert.equal(bits(restored.getDisjunctive()), disj);
  assert.equal(bits(restored.getProfileVector('42')), prof);
}));

test('saving marks the store clean and clearMemory removes the rows', withDb(() => {
  const store = new HDMemoryStore('88', D);
  for (let i = 0; i < 25; i += 1) store.ingestTurn(encodeTurn('a', `t${i}`, i, 'text', D));
  assert.equal(store.needsSave, true);
  store.save(db);
  assert.equal(store.needsSave, false);
  assert.ok(db.getHdMemory('88', 'conjunctive'));

  db.clearMemory('88');
  assert.equal(db.getHdMemory('88', 'conjunctive'), null);
  assert.deepEqual(db.allHdMemory('88'), []);
}));

test('hd_memory blobs are bit-packed, not JSON', withDb(() => {
  const store = new HDMemoryStore('99', 10000);
  store.ingestTurn(encodeTurn('a', 'sizing check', 1, 'text', 10000));
  store.save(db);
  const { bits: got, dim } = db.getHdMemory('99', 'conjunctive');
  assert.equal(dim, 10000);
  assert.equal(got.length, 10000);
  // 10000 bits is 1250 bytes; a JSON array of the same would be ~20KB.
  assert.equal(packBits(got).length, 1250);
}));

// ============================================================================
// 5. Calibration — these pin behaviour that is currently BROKEN
// ============================================================================

test('CALIBRATION: signal prototypes are untrained, so the HD gate does not '
  + 'discriminate signal from chatter', () => {
  // Not an endorsement — a tripwire. The prototypes are random vectors keyed
  // off the literal strings "signal:blocker" etc., with no training step, so a
  // message's similarity to them is noise centred on 0.5 while the threshold
  // sits at ~0.5071. Text that plainly IS a blocker scores below the floor.
  //
  // When someone trains the prototypes, this test SHOULD fail. That is the
  // signal to flip `hd_gate_enabled` on, and to rewrite this test.
  assert.ok(Math.abs(HD_SIM_THRESHOLD - 0.5071) < 0.001, 'threshold moved');

  const realSignal = 'the deploy is blocked, I cannot get past this sqlite error';
  const scores = hdPreclassify(realSignal);
  assert.equal(Object.keys(scores).length, 4);
  assert.equal(hdAnySignal(scores), false,
    'a genuine blocker still scores as noise — prototypes are untrained');

  // And empty input yields nothing at all rather than a spurious pass.
  assert.deepEqual(hdPreclassify('   '), {});
  assert.equal(hdAnySignal({}), false);
});

test('CALIBRATION: the sentinel flags ordinary traffic as anomalous', () => {
  // Conjunctive binding makes any change to any field near-orthogonal, so a
  // message rate drifting 0.50 → 0.51 reads as a severe anomaly. On normal
  // traffic that is the overwhelming majority of events, which is why
  // `sentinel_quarantine` defaults off.
  //
  // Bucket the continuous fields and this should drop sharply — at which point
  // this test fails and the threshold below wants revisiting.
  const s = new DiscordSentinel({ dim: D });
  let quarantined = 0;
  const total = 60;
  for (let i = 0; i < total; i += 1) {
    const rate = (0.5 + (i % 17) * 0.01).toFixed(2);
    const r = s.observe('MESSAGE_BURST', { channel_id: '5', rate, window_seconds: '10' });
    if (r.verdict === 'QUARANTINE') quarantined += 1;
  }
  assert.ok(quarantined / total > 0.8,
    `expected the known false-positive rate, got ${quarantined}/${total}`);

  // The one case it does handle: byte-identical events are recognised.
  const steady = new DiscordSentinel({ dim: D });
  steady.observe('MESSAGE_BURST', { channel_id: '5', rate: '0.50', window_seconds: '10' });
  for (let i = 0; i < 20; i += 1) {
    const r = steady.observe('MESSAGE_BURST', { channel_id: '5', rate: '0.50', window_seconds: '10' });
    assert.equal(r.verdict, 'ALLOW');
  }
});

test('both risky phases are off by default', withDb(() => {
  assert.equal(db.getSetting('1', 'hd_gate_enabled'), false);
  assert.equal(db.getSetting('1', 'sentinel_enabled'), false);
  assert.equal(db.getSetting('1', 'sentinel_quarantine'), false);
}));
